# ⚠️ NOTA: En producción usar Sealed Secrets o External Secrets
# Por ahora plaintext como el resto de tu cluster
apiVersion: v1
kind: Secret
metadata:
  name: autotunchi-secrets
  namespace: autotunchi
  labels:
    app.kubernetes.io/name: autotunchi
    app.kubernetes.io/component: config
type: Opaque
stringData:
  # Database - usando PostgreSQL local en namespace
  DATABASE_URL: "postgresql://autotunchi:autotunchi-secret-2024@postgres.autotunchi.svc.cluster.local:5432/autotunchi"

  # NextAuth - generar con: openssl rand -base64 32
  AUTH_SECRET: "CAMBIAR-generar-con-openssl-rand-base64-32"

  # GitHub OAuth App - crear en github.com/settings/developers
  AUTH_GITHUB_ID: "CAMBIAR"
  AUTH_GITHUB_SECRET: "CAMBIAR"

  # Encryption key - generar con: openssl rand -base64 32
  ENCRYPTION_KEY: "CAMBIAR-generar-con-openssl-rand-base64-32"

  # MinIO credentials (si usas S3 backend para Pulumi)
  MINIO_ACCESS_KEY: ""
  MINIO_SECRET_KEY: ""
---
# PostgreSQL credentials
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: autotunchi
  labels:
    app.kubernetes.io/name: autotunchi
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_USER: "autotunchi"
  POSTGRES_PASSWORD: "autotunchi-secret-2024"
  POSTGRES_DB: "autotunchi"
